# Generated by Django 5.1.4 on 2026-01-25 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human-readable title of the document', max_length=255)),
                ('file', models.FileField(help_text='The original uploaded PDF file', upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(help_text='1-indexed page number within the document')),
                ('text_raw', models.TextField(blank=True, help_text='Original extracted text preserving case and formatting')),
                ('text_norm', models.TextField(blank=True, help_text='Normalized (lowercase) text for case-insensitive search')),
                ('width', models.FloatField(help_text='Page width in PDF points (1 point = 1/72 inch)')),
                ('height', models.FloatField(help_text='Page height in PDF points (1 point = 1/72 inch)')),
                ('rotation', models.IntegerField(default=0, help_text='Page rotation in degrees (0, 90, 180, or 270)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.document')),
            ],
            options={
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='0-indexed position of this chunk within the page')),
                ('chunk_text', models.TextField(help_text='The actual text content of this chunk')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.page')),
            ],
            options={
                'ordering': ['page', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['document', 'page_number'], name='core_page_documen_62217f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('document', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['page', 'chunk_index'], name='core_chunk_page_id_8e2bd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('page', 'chunk_index')},
        ),
    ]
