# Generated by Django 5.1.4 on 2026-01-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], help_text="Who sent this message: 'user' or 'ai'", max_length=10)),
                ('content', models.TextField(help_text='The message content (question or answer text)')),
                ('claims', models.JSONField(blank=True, default=list, help_text='List of citations/claims from AI response (empty for user messages)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='The document this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.document')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='core_chatme_documen_23eedc_idx')],
            },
        ),
    ]
