# Generated by Django 5.1.4 on 2026-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='The original uploaded document file (PDF, DOCX, or PPTX)', upload_to='documents/'),
        ),
    ]
